[manifest]
version = "1.0.0"
dump_lua = true
priority = 0
# Allows floating sprite to be larger than the card
[[patches]]
[patches.pattern]
target = 'engine/sprite.lua'
pattern = "love.graphics.scale(1/(other_obj.scale_mag or other_obj.VT.scale))"
position = 'at'
payload = "love.graphics.scale(1/(other_obj.scale_mag or other_obj.VT.scale) * (self.floating_scale or 1))"
match_indent = true
